---
title: "Notes"
author: "Jonas Hagenberg"
date: "11 4 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Structure of the tutorial
- quick recap what modules need compared to normal Shiny
- situations when dynamically adding modules are handy
  - something has to be repeated based on user input
  - e.g. show several plots or tables
  - a set of UI elements has to be repeated
  - can become complex quite fast -> only use it carefully
- when adding a module, what has to be done?
  - do the following with incremental live coding
  - -> everything in an observer for the actionButton "Add module"
  - add the logic/server function
  - add the UI -> use `insertUI`
  - take care of the module IDs -> explain that you can use the value of the actionButton
- explain jQuery selectors briefly
- what to do when you want to remove a module?
  - remove the UI elements -> `removeUI`
  - to make it easier with the removing -> wrap UI elements of moduleUI in `div`
  with ID
  - try it out with live coding -> problem with IDs
  - explain to use counter for IDs
  - show that it works with the UI elements
- problem: inputs and observers still remain -> maybe show this in console?
  - can lead to unstable apps
  - show solution how to remove module inputs
  - show solution how to remove observers